"""Initial migration

Revision ID: 277d3d51d612
Revises:
Create Date: 2024-11-27 17:06:16.606823

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "277d3d51d612"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
