"""Added IndexingStrategy table

Revision ID: 69bfe9085ecf
Revises: 0a23355650fe
Create Date: 2024-11-20 22:58:55.567261

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "69bfe9085ecf"
down_revision: Union[str, None] = "0a23355650fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "indexing_strategy",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("strategy_name", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_index(
        "flattened_embedding_vector_embedding_idx",
        table_name="flattened_embedding",
        postgresql_using="hnsw",
    )
    op.drop_constraint("page_file_id_fkey", "page", type_="foreignkey")
    op.create_foreign_key(None, "page", "file", ["file_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "page", type_="foreignkey")
    op.create_foreign_key(
        "page_file_id_fkey", "page", "file", ["file_id"], ["id"], ondelete="CASCADE"
    )
    op.create_index(
        "flattened_embedding_vector_embedding_idx",
        "flattened_embedding",
        ["vector_embedding"],
        unique=False,
        postgresql_using="hnsw",
    )
    op.drop_table("indexing_strategy")
    # ### end Alembic commands ###
