"""Updated dim of query embeddings

Revision ID: 03e4d5ae503c
Revises: fd66d94efc77
Create Date: 2024-10-18 13:45:30.314422

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "03e4d5ae503c"
down_revision: Union[str, None] = "fd66d94efc77"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
