"""Updated created_at to datetime type

Revision ID: 10dc6a241fe7
Revises: 5c94d8ddca4b
Create Date: 2024-10-13 06:44:23.151768

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "10dc6a241fe7"
down_revision: Union[str, None] = "5c94d8ddca4b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
