"""Removed dim and embedding_type from Embedding table

Revision ID: 32ff8a468a38
Revises: 93ce4bceb392
Create Date: 2024-10-16 11:49:00.115046

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "32ff8a468a38"
down_revision: Union[str, None] = "93ce4bceb392"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("embedding", "dim")
    op.drop_column("embedding", "embedding_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "embedding",
        sa.Column("embedding_type", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "embedding", sa.Column("dim", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
