"""Use String for types of created_at and last_modified

Revision ID: 5c94d8ddca4b
Revises:
Create Date: 2024-10-13 06:29:19.186267

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5c94d8ddca4b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "file",
        "last_modified",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "file",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.drop_column("file", "filesize")
    op.alter_column(
        "folder",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "page",
        "last_modified",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "page",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "query",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.String(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "created_at",
        existing_type=sa.String(),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "query",
        "created_at",
        existing_type=sa.String(),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "page",
        "created_at",
        existing_type=sa.String(),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "page",
        "last_modified",
        existing_type=sa.String(),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "folder",
        "created_at",
        existing_type=sa.String(),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.add_column(
        "file",
        sa.Column(
            "filesize",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.alter_column(
        "file",
        "created_at",
        existing_type=sa.String(),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "file",
        "last_modified",
        existing_type=sa.String(),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
