"""Added id to each __repr__ of each table

Revision ID: 88e18284cc13
Revises: ed87483f811a
Create Date: 2024-11-13 11:30:18.258099

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "88e18284cc13"
down_revision: Union[str, None] = "ed87483f811a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "flattened_embedding_binary_quantize_idx",
        table_name="flattened_embedding",
        postgresql_using="hnsw",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "flattened_embedding_binary_quantize_idx",
        "flattened_embedding",
        [sa.text("(binary_quantize(vector_embedding)::bit(128))")],
        unique=False,
        postgresql_using="hnsw",
    )
    # ### end Alembic commands ###
