"""Updated vector type to vector[]

Revision ID: 93ce4bceb392
Revises: d496c0cb4a5b
Create Date: 2024-10-13 18:31:31.518511

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "93ce4bceb392"
down_revision: Union[str, None] = "d496c0cb4a5b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
