"""Made text_content, binary_content, and summary optional

Revision ID: d496c0cb4a5b
Revises: 10dc6a241fe7
Create Date: 2024-10-13 13:39:59.871458

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d496c0cb4a5b"
down_revision: Union[str, None] = "10dc6a241fe7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("file", "summary", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("page", "text_content", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "page", "binary_content", existing_type=postgresql.BYTEA(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "page", "binary_content", existing_type=postgresql.BYTEA(), nullable=False
    )
    op.alter_column("page", "text_content", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("file", "summary", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
