"""Added last_modified and created_at to Embedding

Revision ID: eb81047b04ce
Revises: 32ff8a468a38
Create Date: 2024-10-16 15:43:59.612908

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eb81047b04ce"
down_revision: Union[str, None] = "32ff8a468a38"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("embedding", sa.Column("last_modified", sa.String(), nullable=False))
    op.add_column("embedding", sa.Column("created_at", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("embedding", "created_at")
    op.drop_column("embedding", "last_modified")
    # ### end Alembic commands ###
