"""Added FlattenedEmbedding table

Revision ID: fd66d94efc77
Revises: eb81047b04ce
Create Date: 2024-10-16 15:47:01.916274

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = "fd66d94efc77"
down_revision: Union[str, None] = "eb81047b04ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flattened_embedding",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "vector_embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=128),
            nullable=False,
        ),
        sa.Column("last_modified", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("embedding_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["embedding_id"],
            ["embedding.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("flattened_embedding")
    # ### end Alembic commands ###
