"""Renamed QueryCache to Search with result and response

Revision ID: a341fb646fcd
Revises: a4cd6bacdccf
Create Date: 2024-11-26 20:20:40.822261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a341fb646fcd'
down_revision: Union[str, None] = 'a4cd6bacdccf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('response', sa.String(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_id'), 'search', ['id'], unique=False)
    op.create_index(op.f('ix_search_query'), 'search', ['query'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_query'), table_name='search')
    op.drop_index(op.f('ix_search_id'), table_name='search')
    op.drop_table('search')
    # ### end Alembic commands ###
